# Generated by Django 3.2.20 on 2023-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230821_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Badam', max_length=255),
            preserve_default=False,
        ),
    ]
